= Join Scepta
Gary Brown
2015-02-27
:jbake-type: page
:jbake-status: published
:jbake-tags: community
:description: You are interested in Scepta and would like to know where to start?

== Meet the developers

There are several ways to join the Scepta community. The best option is always to talk to people and see what is
going on. There are several ways to reach the developers and other community members.

=== IRC

The Scepta developers hang around on Internet Relay Chat (Irc) on irc://irc.freenode.net/#jbossoverlord[irc://irc.freenode
.net/#jbossoverlord] (check here of a http://webchat.freenode.net/?channels=jbossoverlord[Web-client] if you can't use a irc
client on your machine).


== Contribute code

All code lives on GitHub under https://github.com/scepta[https://github.com/scepta]. To contribute, fork the
respective project(s), implement your changes and open a pull-request.


== Contribute documentation

Similar to code, the Scepta website and documentation lives under
https://github.com/scepta.github.io[https://github.com/scepta.github.io]. And as with the code,
fork the repo, create your changes and open a pull-request.



